#!/usr/bin/env python3
from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "datasets" / "cinegacha-films" / "dataset.json"

NAMES = [
    "Harakiri", "Come and See", "Seven Samurai", "12 Angry Men", "The Godfather", "Parasite",
    "Spirited Away", "The Human Condition III", "High and Low", "The Godfather Part II",
    "The Shawshank Redemption", "City of God", "Yi Yi", "The Apartment", "A Brighter Summer Day",
    "The Good, the Bad and the Ugly", "The Lord of the Rings: The Return of the King", "Schindler's List",
    "The Passion of Joan of Arc", "Ikiru", "Tokyo Story", "The Cranes Are Flying", "Stalker",
    "The Handmaiden", "Portrait of a Lady on Fire", "Whiplash", "La Haine", "Memories of Murder",
    "Cinema Paradiso", "In the Mood for Love", "The Dark Knight", "The Thing", "Oldboy",
    "Apocalypse Now", "Ran", "Pather Panchali", "The 400 Blows", "Mirror", "Goodfellas",
    "The Empire Strikes Back", "Princess Mononoke", "Do the Right Thing", "There Will Be Blood",
    "The Red Shoes", "Barry Lyndon", "Fanny and Alexander", "Andrei Rublev", "Perfect Blue",
    "The Silence of the Lambs", "Rear Window", "Sunset Boulevard", "Paths of Glory", "Chungking Express",
    "The Matrix", "Alien", "The Shining", "Mulholland Drive", "The Young Girls of Rochefort",
    "Le Samourai", "The Wages of Fear", "Pulp Fiction", "Fallen Angels", "The Grand Budapest Hotel",
    "Rashomon", "Nights of Cabiria", "The Seventh Seal", "M", "The Battle of Algiers",
    "Once Upon a Time in the West", "Sherlock Jr.", "Tampopo", "Before Sunrise", "Before Sunset",
    "Before Midnight", "The Tale of the Princess Kaguya", "Wolf Children", "Your Name.", "A Separation",
    "The Lives of Others", "The Hunt", "Amadeus", "Stop Making Sense", "Paris, Texas",
    "Wild Strawberries", "Bicycle Thieves", "The General", "Singin' in the Rain", "The Lion King",
    "Toy Story", "WALL-E", "Ratatouille", "Up", "Spider-Man: Into the Spider-Verse", "Akira",
    "Ghost in the Shell", "Nausicaa of the Valley of the Wind", "My Neighbor Totoro", "Kiki's Delivery Service",
    "Howl's Moving Castle", "Castle in the Sky", "Grave of the Fireflies", "Millennium Actress",
    "Paprika", "Tokyo Godfathers", "The End of Evangelion", "Evangelion: 3.0+1.0 Thrice Upon a Time",
    "Drive My Car", "Shoplifters", "Still Walking", "Nobody Knows", "Burning", "Decision to Leave",
    "Joint Security Area", "The Wailing", "Mother", "The Host", "Train to Busan", "Past Lives",
    "Aftersun", "Moonlight", "The Florida Project", "Lady Bird", "Little Women", "Get Out",
    "Hereditary", "Midsommar", "Uncut Gems", "Good Time", "Eternal Sunshine of the Spotless Mind",
    "Synecdoche, New York", "Being John Malkovich", "Adaptation.", "Magnolia", "Boogie Nights",
    "Punch-Drunk Love", "Licorice Pizza", "Phantom Thread", "No Country for Old Men", "Fargo",
    "The Big Lebowski", "Inside Llewyn Davis", "O Brother, Where Art Thou?", "The Social Network",
    "Zodiac", "Se7en", "Fight Club", "Gone Girl", "Heat", "Collateral", "Thief", "The Insider",
    "Mad Max: Fury Road", "Children of Men", "Pan's Labyrinth", "Y Tu Mama Tambien", "Roma",
    "Amores Perros", "The Worst Person in the World", "Oslo, August 31st", "Another Round",
    "The Celebration", "Persona", "Cries and Whispers", "Autumn Sonata", "Scenes from a Marriage",
    "Cleo from 5 to 7", "Vagabond", "Beau Travail", "The Gleaners and I", "Jeanne Dielman",
    "News from Home", "Daisies", "Meshes of the Afternoon", "A Woman Under the Influence",
    "Opening Night", "Love Streams", "Mikey and Nicky", "The Night of the Hunter", "Touch of Evil",
    "Citizen Kane", "Casablanca", "It's a Wonderful Life", "Some Like It Hot", "The Third Man",
    "Notorious", "Vertigo", "Psycho", "North by Northwest", "The Birds", "Jaws", "Jurassic Park",
    "Raiders of the Lost Ark", "E.T. the Extra-Terrestrial", "Close Encounters of the Third Kind",
    "Back to the Future", "Terminator 2: Judgment Day", "Die Hard", "Blade Runner", "Brazil",
    "The Truman Show", "The Green Mile", "Forrest Gump", "Saving Private Ryan", "Gladiator",
    "Crouching Tiger, Hidden Dragon", "Hero", "House of Flying Daggers", "The Farewell", "Minari",
]

DIRECTORS = {
    "Harakiri": "Masaki Kobayashi",
    "Come and See": "Elem Klimov",
    "Seven Samurai": "Akira Kurosawa",
    "12 Angry Men": "Sidney Lumet",
    "The Godfather": "Francis Ford Coppola",
    "Parasite": "Bong Joon-ho",
    "Spirited Away": "Hayao Miyazaki",
    "The Human Condition III": "Masaki Kobayashi",
    "High and Low": "Akira Kurosawa",
    "The Godfather Part II": "Francis Ford Coppola",
    "The Shawshank Redemption": "Frank Darabont",
    "City of God": "Fernando Meirelles and Katia Lund",
    "Yi Yi": "Edward Yang",
    "The Apartment": "Billy Wilder",
    "A Brighter Summer Day": "Edward Yang",
    "The Good, the Bad and the Ugly": "Sergio Leone",
    "The Lord of the Rings: The Return of the King": "Peter Jackson",
    "Schindler's List": "Steven Spielberg",
    "The Passion of Joan of Arc": "Carl Theodor Dreyer",
    "Ikiru": "Akira Kurosawa",
    "Tokyo Story": "Yasujiro Ozu",
    "The Cranes Are Flying": "Mikhail Kalatozov",
    "Stalker": "Andrei Tarkovsky",
    "The Handmaiden": "Park Chan-wook",
    "Portrait of a Lady on Fire": "Celine Sciamma",
    "Whiplash": "Damien Chazelle",
    "La Haine": "Mathieu Kassovitz",
    "Memories of Murder": "Bong Joon-ho",
    "Cinema Paradiso": "Giuseppe Tornatore",
    "In the Mood for Love": "Wong Kar-wai",
    "The Dark Knight": "Christopher Nolan",
    "The Thing": "John Carpenter",
    "Oldboy": "Park Chan-wook",
    "Apocalypse Now": "Francis Ford Coppola",
    "Ran": "Akira Kurosawa",
    "Pather Panchali": "Satyajit Ray",
    "The 400 Blows": "Francois Truffaut",
    "Mirror": "Andrei Tarkovsky",
    "Goodfellas": "Martin Scorsese",
    "The Empire Strikes Back": "Irvin Kershner",
    "Princess Mononoke": "Hayao Miyazaki",
    "Do the Right Thing": "Spike Lee",
    "There Will Be Blood": "Paul Thomas Anderson",
    "The Red Shoes": "Michael Powell and Emeric Pressburger",
    "Barry Lyndon": "Stanley Kubrick",
    "Fanny and Alexander": "Ingmar Bergman",
    "Andrei Rublev": "Andrei Tarkovsky",
    "Perfect Blue": "Satoshi Kon",
    "The Silence of the Lambs": "Jonathan Demme",
    "Rear Window": "Alfred Hitchcock",
    "Sunset Boulevard": "Billy Wilder",
    "Paths of Glory": "Stanley Kubrick",
    "Chungking Express": "Wong Kar-wai",
    "The Matrix": "Lana Wachowski and Lilly Wachowski",
    "Alien": "Ridley Scott",
    "The Shining": "Stanley Kubrick",
    "Mulholland Drive": "David Lynch",
    "The Young Girls of Rochefort": "Jacques Demy",
    "Le Samourai": "Jean-Pierre Melville",
    "The Wages of Fear": "Henri-Georges Clouzot",
    "Pulp Fiction": "Quentin Tarantino",
    "Fallen Angels": "Wong Kar-wai",
    "The Grand Budapest Hotel": "Wes Anderson",
    "Rashomon": "Akira Kurosawa",
    "Nights of Cabiria": "Federico Fellini",
    "The Seventh Seal": "Ingmar Bergman",
    "M": "Fritz Lang",
    "The Battle of Algiers": "Gillo Pontecorvo",
    "Once Upon a Time in the West": "Sergio Leone",
    "Sherlock Jr.": "Buster Keaton",
    "Tampopo": "Juzo Itami",
    "Before Sunrise": "Richard Linklater",
    "Before Sunset": "Richard Linklater",
    "Before Midnight": "Richard Linklater",
    "The Tale of the Princess Kaguya": "Isao Takahata",
    "Wolf Children": "Mamoru Hosoda",
    "Your Name.": "Makoto Shinkai",
    "A Separation": "Asghar Farhadi",
    "The Lives of Others": "Florian Henckel von Donnersmarck",
    "The Hunt": "Thomas Vinterberg",
    "Amadeus": "Milos Forman",
    "Stop Making Sense": "Jonathan Demme",
    "Paris, Texas": "Wim Wenders",
    "Wild Strawberries": "Ingmar Bergman",
    "Bicycle Thieves": "Vittorio De Sica",
    "The General": "Buster Keaton and Clyde Bruckman",
    "Singin' in the Rain": "Gene Kelly and Stanley Donen",
    "The Lion King": "Roger Allers and Rob Minkoff",
    "Toy Story": "John Lasseter",
    "WALL-E": "Andrew Stanton",
    "Ratatouille": "Brad Bird",
    "Up": "Pete Docter",
    "Spider-Man: Into the Spider-Verse": "Bob Persichetti, Peter Ramsey and Rodney Rothman",
    "Akira": "Katsuhiro Otomo",
    "Ghost in the Shell": "Mamoru Oshii",
    "Nausicaa of the Valley of the Wind": "Hayao Miyazaki",
    "My Neighbor Totoro": "Hayao Miyazaki",
    "Kiki's Delivery Service": "Hayao Miyazaki",
    "Howl's Moving Castle": "Hayao Miyazaki",
    "Castle in the Sky": "Hayao Miyazaki",
    "Grave of the Fireflies": "Isao Takahata",
    "Millennium Actress": "Satoshi Kon",
    "Paprika": "Satoshi Kon",
    "Tokyo Godfathers": "Satoshi Kon",
    "The End of Evangelion": "Hideaki Anno and Kazuya Tsurumaki",
    "Evangelion: 3.0+1.0 Thrice Upon a Time": "Hideaki Anno",
    "Drive My Car": "Ryusuke Hamaguchi",
    "Shoplifters": "Hirokazu Kore-eda",
    "Still Walking": "Hirokazu Kore-eda",
    "Nobody Knows": "Hirokazu Kore-eda",
    "Burning": "Lee Chang-dong",
    "Decision to Leave": "Park Chan-wook",
    "Joint Security Area": "Park Chan-wook",
    "The Wailing": "Na Hong-jin",
    "Mother": "Bong Joon-ho",
    "The Host": "Bong Joon-ho",
    "Train to Busan": "Yeon Sang-ho",
    "Past Lives": "Celine Song",
    "Aftersun": "Charlotte Wells",
    "Moonlight": "Barry Jenkins",
    "The Florida Project": "Sean Baker",
    "Lady Bird": "Greta Gerwig",
    "Little Women": "Greta Gerwig",
    "Get Out": "Jordan Peele",
    "Hereditary": "Ari Aster",
    "Midsommar": "Ari Aster",
    "Uncut Gems": "Josh Safdie and Benny Safdie",
    "Good Time": "Josh Safdie and Benny Safdie",
    "Eternal Sunshine of the Spotless Mind": "Michel Gondry",
    "Synecdoche, New York": "Charlie Kaufman",
    "Being John Malkovich": "Spike Jonze",
    "Adaptation.": "Spike Jonze",
    "Magnolia": "Paul Thomas Anderson",
    "Boogie Nights": "Paul Thomas Anderson",
    "Punch-Drunk Love": "Paul Thomas Anderson",
    "Licorice Pizza": "Paul Thomas Anderson",
    "Phantom Thread": "Paul Thomas Anderson",
    "No Country for Old Men": "Joel Coen and Ethan Coen",
    "Fargo": "Joel Coen and Ethan Coen",
    "The Big Lebowski": "Joel Coen and Ethan Coen",
    "Inside Llewyn Davis": "Joel Coen and Ethan Coen",
    "O Brother, Where Art Thou?": "Joel Coen and Ethan Coen",
    "The Social Network": "David Fincher",
    "Zodiac": "David Fincher",
    "Se7en": "David Fincher",
    "Fight Club": "David Fincher",
    "Gone Girl": "David Fincher",
    "Heat": "Michael Mann",
    "Collateral": "Michael Mann",
    "Thief": "Michael Mann",
    "The Insider": "Michael Mann",
    "Mad Max: Fury Road": "George Miller",
    "Children of Men": "Alfonso Cuaron",
    "Pan's Labyrinth": "Guillermo del Toro",
    "Y Tu Mama Tambien": "Alfonso Cuaron",
    "Roma": "Alfonso Cuaron",
    "Amores Perros": "Alejandro G. Inarritu",
    "The Worst Person in the World": "Joachim Trier",
    "Oslo, August 31st": "Joachim Trier",
    "Another Round": "Thomas Vinterberg",
    "The Celebration": "Thomas Vinterberg",
    "Persona": "Ingmar Bergman",
    "Cries and Whispers": "Ingmar Bergman",
    "Autumn Sonata": "Ingmar Bergman",
    "Scenes from a Marriage": "Ingmar Bergman",
    "Cleo from 5 to 7": "Agnes Varda",
    "Vagabond": "Agnes Varda",
    "Beau Travail": "Claire Denis",
    "The Gleaners and I": "Agnes Varda",
    "Jeanne Dielman": "Chantal Akerman",
    "News from Home": "Chantal Akerman",
    "Daisies": "Vera Chytilova",
    "Meshes of the Afternoon": "Maya Deren and Alexander Hammid",
    "A Woman Under the Influence": "John Cassavetes",
    "Opening Night": "John Cassavetes",
    "Love Streams": "John Cassavetes",
    "Mikey and Nicky": "Elaine May",
    "The Night of the Hunter": "Charles Laughton",
    "Touch of Evil": "Orson Welles",
    "Citizen Kane": "Orson Welles",
    "Casablanca": "Michael Curtiz",
    "It's a Wonderful Life": "Frank Capra",
    "Some Like It Hot": "Billy Wilder",
    "The Third Man": "Carol Reed",
    "Notorious": "Alfred Hitchcock",
    "Vertigo": "Alfred Hitchcock",
    "Psycho": "Alfred Hitchcock",
    "North by Northwest": "Alfred Hitchcock",
    "The Birds": "Alfred Hitchcock",
    "Jaws": "Steven Spielberg",
    "Jurassic Park": "Steven Spielberg",
    "Raiders of the Lost Ark": "Steven Spielberg",
    "E.T. the Extra-Terrestrial": "Steven Spielberg",
    "Close Encounters of the Third Kind": "Steven Spielberg",
    "Back to the Future": "Robert Zemeckis",
    "Terminator 2: Judgment Day": "James Cameron",
    "Die Hard": "John McTiernan",
    "Blade Runner": "Ridley Scott",
    "Brazil": "Terry Gilliam",
    "The Truman Show": "Peter Weir",
    "The Green Mile": "Frank Darabont",
    "Forrest Gump": "Robert Zemeckis",
    "Saving Private Ryan": "Steven Spielberg",
    "Gladiator": "Ridley Scott",
    "Crouching Tiger, Hidden Dragon": "Ang Lee",
    "Hero": "Zhang Yimou",
    "House of Flying Daggers": "Zhang Yimou",
    "The Farewell": "Lulu Wang",
    "Minari": "Lee Isaac Chung",
}


def slugify(name: str) -> str:
    return "".join(c.lower() if c.isalnum() else "-" for c in name).strip("-").replace("--", "-")


def main() -> None:
    items = []
    raw = []
    for index, name in enumerate(NAMES[:200]):
        rating = round(4.72 - index * 0.0028 + ((index % 7) - 3) * 0.006, 2)
        reviews = int(420000 - index * 1450 + (index % 11) * 5300)
        score = (rating / 5) * math.log(max(reviews, 1))
        raw.append((score, name, rating, reviews))
    thresholds = sorted([score for score, *_ in raw], reverse=True)
    for score, name, rating, reviews in raw:
        rank = thresholds.index(score) / len(thresholds)
        rarity = "L" if rank < .02 else "UR" if rank < .10 else "R" if rank < .30 else "UC" if rank < .60 else "C"
        items.append({
            "id": slugify(name),
            "name": name,
            "image": f"/api/poster/{slugify(name)}",
            "director": DIRECTORS.get(name, "Realisateur a renseigner"),
            "rating": rating,
            "reviewCount": reviews,
            "rarity": rarity,
        })
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({
        "id": "cinegacha-films",
        "name": "CinéGacha Films",
        "dropRates": {"C": 55, "UC": 28, "R": 12, "UR": 4, "L": 1},
        "items": items,
    }, ensure_ascii=True, indent=2), encoding="utf-8")
    print(f"Wrote {OUT} with {len(items)} items")


if __name__ == "__main__":
    main()
